version: '3.7'

services:
  keycloackauth-api:
    build:
      context: .
      dockerfile: KeycloackAuth.Api/Dockerfile
    ports:
      - 54217:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      KEYCLOAK_SERVER_URL: http://localhost:8080/keycloak
      KEYCLOAK_REALM: dev
      CLIENT_ID: "oauth-api"
      CLIENT_SECRET: "DoGBgIVzsTV4HOhIBZgFDHmj7g232AbD"
    networks:
      - keycloak-network

networks:
  keycloak-network: