version: '3.7'

services:
  keycloackauth-api:
    build:
      context: .
      dockerfile: KeycloackAuth.Api/Dockerfile
    ports:
      - 54217:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      KEYCLOAK_SERVER_URL: {{YOUR_SERVER_URL}}
      KEYCLOAK_REALM: {{YOUR_REALM}}
      CLIENT_ID: {{YOUR_CLIENT_ID}}
      CLIENT_SECRET: {{YOUR_CLIENT_SECRET}}
    networks:
      - keycloak-network

networks:
  keycloak-network: