version: '3.7'

services:
  keycloackauth-api:
    build:
      context: .
      dockerfile: KeycloackAuth.Api/Dockerfile
    ports:
      - 54217:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      KEYCLOAK_SERVER_URL: ""
      KEYCLOAK_REALM: sisfolha-dev
      CLIENT_ID: "oauth-api"
      CLIENT_SECRET: "b2qdFcSzjhHW5ONsxrgYYyQQiYtrX2tB"
    networks:
      - keycloak-network

networks:
  keycloak-network: