version: '3.7'

services:
  keycloackauth-api:
    image: ${DOCKER_REGISTRY-}keycloackauth-api
    build:
      context: .
      dockerfile: KeycloackAuth.Api/Dockerfile
    networks:
      - keycloak-network

networks:
  keycloak-network: